apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels: 
    app: backend
spec:
  replicas:
  selector: 
    matchLabels:
      app: backend
  teplate:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: registry.hiriko.local:5000/back:24
        ports:
        - containerPort: 5000