apiVersion: apps/v1
kind: Deployment
metadata:
  name: db_postgre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db_postgre
  template:
    metadata:
      labels:
        app: db_postgre
    spec:
      containers:
        - name: db_postgre
          image: registry.hiriko.local:5000/postgres:11.2-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db_postgre
      volumes:
        - name: db_postgre
          persistentVolumeClaim:
            claimName: postgres-pv-claim